catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from catalog.apps import MainappConfig
from catalog.views import ProductListView, ContactsListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleCreateView

app_name = MainappConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    # path('page/<int:page_number>/', ProductListView.as_view(), name='paginator'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('products/create', ProductCreateView.as_view(), name='products_create'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:pk>/delete', ProductDeleteView.as_view(), name='products_delete'),
    path('blog', ArticleListView.as_view(), name='article_list'),
    path('<slug:slug>', ArticleDetailView.as_view(), name='article_detail'),
    path('article/create', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, UserInvalidEmail

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password-reset/', UserPasswordResetView.as_view(), name='password-reset'),
    path("invalid-email/", UserInvalidEmail.as_view(), name="invalid-email"),
]

catalog/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from users.models import User


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True, verbose_name='Категория товара')
    category_description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='Наименование товара')
    product_description = models.TextField(verbose_name='Описание')
    product_picture = models.ImageField(upload_to='products_images', blank=True, null=True, verbose_name='Фото')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Категория товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    created_at = models.DateTimeField(verbose_name='Дата создания', default=datetime.now)
    updated_at = models.DateTimeField(verbose_name='Дата изменения', default=datetime.now)
    views_counter = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    owner = models.ForeignKey(User, verbose_name="Создатель", blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Товары'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.product_name


class Contacts(models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    phone_number = models.CharField(max_length=12, verbose_name='Phone')
    message = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(null=False, unique=True)
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog', null=True, blank=True, verbose_name='Изображение')
    created_at = models.DateTimeField(verbose_name='Дата создания', default=datetime.now)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    views_counter = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

    def get_absolute_url(self):
        return reverse('catalog:article_detail', kwargs={'slug': self.slug})


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, verbose_name='Продукт', null=True, blank=True)
    version_number = models.PositiveIntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    class Meta:
        verbose_name = 'Версия товара'
        verbose_name_plural = 'Версии товаров'

    def __str__(self):
        return f"Версия: {self.version_number} - {self.version_name}"

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField
from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ("views_counter", "created_at", "updated_at", "owner")

    def clean_product_name(self):
        product_name = self.cleaned_data["product_name"]

        banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

        for word in product_name.split():
            if word in banned_words:
                raise ValidationError("Название продукта содержит запрещенные слова.")
        return product_name

    def clean_product_description(self):
        product_description = self.cleaned_data["product_description"]

        banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

        for word in product_description.split():
            if word in banned_words:
                raise ValidationError("Описание продукта содержит запрещенные слова.")
        return product_description


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Contacts, Product, Category, Article, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator


class ProductListView(ListView):
    model = Product
    # paginate_by = 6

    def get_context_data(self, *args, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)

        for product in context_data['object_list']:
            active_version = Version.objects.filter(product=product, is_active=True).first()
            product.active_version = active_version
        return context_data


class ContactsListView(ListView):
    model = Contacts


class ContactCreateView(CreateView):
    model = Contacts
    success_url = reverse_lazy('catalog:home')


class ProductDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(UpdateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data["formset"] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductDeleteView(DeleteView, LoginRequiredMixin):
    model = Product
    success_url = reverse_lazy('catalog:home')


class ArticleListView(ListView):
    model = Article


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    fields = ("title", "body", "preview", "is_published")
    success_url = reverse_lazy('catalog:article_detail')

    def get_success_url(self):
        return reverse('catalog:article_detail', args=[self.object.slug])

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class ArticleUpdateView(UpdateView):
    model = Article

    fields = ("title", "slug", "body", "preview", "is_published")
    success_url = reverse_lazy('catalog:article_list')


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('catalog:article_list')

catalog/templates/catalog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить {{ object.title }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'catalog:article_list' %}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-image">
            <img src="{{ object.preview | media_filter }}">
        </div>
        <div class="card-body">
            <p>{{ object.body }}</p>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:article_list' %}">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/article_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<a type="button" class="btn btn-lg btn-block btn-outline-primary"
   href="{% url 'catalog:article_create' %}">Создать статью</a>
{% for article in object_list %}
{% if article.is_published %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
        </div>
        <div class="card-image">
            <img class="img-same-size" src="{{ article.preview | media_filter }}">
        </div>
        <div class="card-body">
            <p>{{ article.body | truncatechars:200 }}</p>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{{ article.get_absolute_url }}">Посмотреть</a>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'catalog:article_update' article.pk %}">Изменить</a>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'catalog:article_delete' article.pk %}">Удалить</a>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
</head>
<body>
<!-- navbar -->
{% include 'catalog/includes/inc_navbar.html' %}
<!-- header -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
</div>
<!-- cards -->
<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>
    <!-- footer -->
    {% include 'catalog/includes/inc_footer.html' %}
</div>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_item.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-4">
            <h2>{{ object.title }}</h2>
            <p>{{ object.body }}</p>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/contacts_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<!-- header -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<!-- table -->
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <!-- form -->
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone_number" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить {{ object.product_name }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'catalog:home' %}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-image">
            <img src="{{ object.product_picture | media_filter }}">
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.price }} ₽</h1>
            <p>{{ object.product_description }}</p>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:home' %}">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    {% if object %}
                    <h3 class="card-text">Редактирование товара </h3>
                    {% else %}
                    <h3 class="card-text">Создание нового товара</h3>
                    {% endif %}
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <h3 class="card-text">Версия товара</h3>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% for product in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ product.product_name }}</h4>
        </div>
        <div class="card-image">
            <img class="img-same-size" src="{{ product.product_picture | media_filter }}">
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ product.price }} ₽</h1>
            <p>{{ product.product_description | truncatechars:100 }}</p>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'catalog:product_detail' product.pk %}">Посмотреть</a>
            {% if user.is_authenticated %}
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'catalog:products_update' product.pk %}">Изменить</a>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'catalog:products_delete' product.pk %}">Удалить</a>
            {% endif %}
        </div>
        <div class="card-footer">
            {% if product.active_version %}
            <p>{{ product.active_version }}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% include 'catalog/includes/inc_paginator.html' %}
{% endblock %}